print('Parker')
print('Maira')
print('Natasha')
print('this is ki wan!')
print('Jasmine')
print('Eric')
print('Sarah')
print('Kat')
print('Brian')
print('Kristen')
print('Gabe')
print('Sonali')
print('Mélisande')
print("Lee!")